name: Fork Sync

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-18.04
    steps:
      - name: Fetch the master branch
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Fork Sync With Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
        with:
          upstream_repository: citizenfx/cfx-server-data
          upstream_branch: master
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_pull_args: --ff-only
